spring:
  application:
    name: ${NAME:rainbowletter-api}
    version: ${VERSION:local}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: ${DATABASE_DRIVER:com.mysql.cj.jdbc.Driver}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
server:
  port: ${PORT:8080}
jwt:
  secret: ${JWT_SECRET}
cloud:
  aws:
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}
    region: ${AWS_REGION:ap-northeast-2}
    s3:
      bucket: ${BUCKET_NAME}

slack:
  webhook:
    url: ${SLACK_WEBHOOK_URL}
