spring:
  application:
    name: ${NAME:rainbowletter-api}
    version: ${VERSION:local}
server:
  port: ${PORT:8080}
jwt:
  secret: ${JWT_SECRET}
cloud:
  aws:
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}
    region: ${AWS_REGION:ap-northeast-2}
    s3:
      bucket: ${BUCKET_NAME:rainbowletter}